stages:

  data_visualization:
    cmd: python src/visualization/visualize.py --path_to_raw_data data/raw/winequality-red.csv --path_to_save_figs reports/figures
    deps:
      - data/raw/winequality-red.csv
    outs:
      - reports/figures/fixed_acidity.png
      - reports/figures/volatile_acidity.png
      - reports/figures/citric_acid.png
      - reports/figures/residual_sugar.png
      - reports/figures/chlorides.png
      - reports/figures/free_sulfur_dioxide.png
      - reports/figures/total_sulfur_dioxide.png
      - reports/figures/sulphates.png
      - reports/figures/alcohol.png

  prepare_data:
    cmd: python src/data/make_dataset.py --input_filepath data/raw/winequality-red.csv --output_filepath data/processed/
    deps:
      - data/raw/winequality-red.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
