stages:

  data_visualization:
    cmd: python src/visualization/visualize.py --path_to_raw_data data/raw/winequality-red.csv --path_to_save_figs reports/figures
    deps:
      - data/raw/winequality-red.csv
      - src/visualization/visualize.py
    outs:
      - reports/figures/fixed_acidity.png
      - reports/figures/volatile_acidity.png
      - reports/figures/citric_acid.png
      - reports/figures/residual_sugar.png
      - reports/figures/chlorides.png
      - reports/figures/free_sulfur_dioxide.png
      - reports/figures/total_sulfur_dioxide.png
      - reports/figures/sulphates.png
      - reports/figures/alcohol.png

  prepare_data:
    cmd: python src/data/make_dataset.py --input_filepath data/raw/winequality-red.csv --output_filepath data/processed/
    deps:
      - data/raw/winequality-red.csv
      - src/data/make_dataset.py
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train_the_model:
    cmd: python src/models/train_model.py --path_to_dataset data/processed/train.csv --path_to_model_storage models/ --path_to_metrics_storage reports/metrics
    params:
      - train.C
      - train.penalty
    deps:
      - params.yaml
      - data/processed/train.csv
      - src/models/train_model.py
    outs:
      - models/finalized_model.pkl
      - reports/features_importance/shap_values.png
    metrics:
      - reports/metrics/hyper_params.json:
          cache: false

  evaluation:
    cmd: python src/models/validate_model.py --path_to_dataset data/processed/test.csv --path_to_model_pkl models/finalized_model.pkl --path_to_metrics_storage reports/metrics
    deps:
      - data/processed/test.csv
      - models/finalized_model.pkl
      - src/models/validate_model.py
    metrics:
      - reports/metrics/metrics.json:
          cache: false
    plots:
      - reports/metrics/plots.json
