apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
  labels:
    app: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
        - image: grac20101/aleksandr-gordeev:service
          name: service
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: inference-config
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: inference-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://127.0.0.1:30090
            - name: MLFLOW_TRACKING_URI
              value: http://127.0.0.1:30501
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: inference
  labels:
    app: inference
spec:
  selector:
    app: inference
  type: NodePort
  ports:
    - name: "inference-port"
      port: 8081
      targetPort: 80
      nodePort: 30081

