apiVersion: apps/v1

kind: Deployment

metadata:
  labels:
    io.kompose.service: training
  name: training

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: training
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/s3: "true"
        io.kompose.service: training
    spec:
      containers:
        - args:
            - /bin/bash
          env:
            - name: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://nginx:9000
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000
          image: training_scripts_image
          name: training-scripts
          resources: {}
      restartPolicy: Always

status: {}
