apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: grac20101/aleksandr-gordeev:mlflow_server
          args: [
              "mlflow",
              "server",
              "--backend-store-uri",
              "postgresql://gracikk:admin@db-service:5432/mlflow_db",
              "--default-artifact-root",
              "s3://ml-ops",
              "--host", "0.0.0.0"
          ]
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mlflow-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: POSTGRES_DB
            - name: AWS_S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: AWS_S3_BUCKET
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: MLFLOW_S3_ENDPOINT_URL
          ports:
            - containerPort: 5000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  labels:
    app: mlflow
spec:
  selector:
    app: mlflow
  type: NodePort
  ports:
    - name: "mlflow-port"
      port: 5001
      targetPort: 5000
      nodePort: 30501
